config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show]
  resources :bookings, only: [:new, :create, :edit, :update, :destroy] do
    member do
      post :approve
      post :decline
  end
end
  resources :bookings, only: [:show] do
    resources :messages, only: :create
  end
  resources :reviews, only: [:new, :create, :destroy]
  resources :dashboards, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :nanny, class_name: "User", foreign_key: "nanny_id", primary_key: :id
  belongs_to :parent, class_name: "User", foreign_key: "parent_id", primary_key: :id
  has_many :messages, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :booking
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :nanny, class_name: "User", foreign_key: "nanny_id", primary_key: :id
  belongs_to :parent, class_name: "User", foreign_key: "parent_id", primary_key: :id
end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :reviews
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address bio photo price max_cap number_of_kids can_host is_nanny year_of_birth])
  end
end

# app/controllers/application_controller.rb

def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking_index, only: %i[show edit update destroy approve decline]

  def show
    @message = Message.new
  end

  def new
    @booking = Booking.new
    @user_nanny = User.find(params[:nanny_id])
    @booking.nanny = @user_nanny
  end

  def create
    @user_nanny = User.find(params[:booking][:nanny_id])
    @booking = Booking.new(booking_params)
    @booking.parent = current_user
    @booking.status = "pending"

    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboards_path
  end

  def approve
    @booking.status = "confirmed"
    @booking.save!
    redirect_to dashboards_path
  end

  def decline
    @booking.status = "declined"
    destroy
    redirect_to dashboards_path
  end

  private

  def find_booking_index
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :nanny_id)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @message = Message.new
    @chatroom = Chatroom.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @review = Review.new
    @parent = current_user
    if current_user.is_nanny == false
      @bookings = Booking.where(parent: current_user)
    elsif current_user.is_nanny == true
      @bookings = Booking.where(nanny: current_user)
    end
    @schedule = helpers.events_hash(Booking.where(parent: current_user), :parent)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @booking = Booking.find(params[:booking_id])

    @message.booking = @booking
    @message.user = current_user

    if @message.save
      # Broadcast to all subscribers!
      BookingChannel.broadcast_to(
        @booking,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to booking_path(@booking, anchor: "message-#{@message.id}")
    else
      render 'bookings/show'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # @review = Review.new
    # @user_nanny = User.find(params[:nanny_id])
    # @review.nanny = @user_nanny
  end

  def create
    @user_nanny = User.find(params[:review][:nanny_id])
    @review = Review.new(review_params)
    @review.parent = current_user

    if @review.save!
      redirect_to dashboards_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :nanny_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :find_index, only: %i[show]

  def index
    @users = User.all
    @user = current_user
    if params[:query].present?
      @users = User.where("address ILIKE ?", "%#{params[:query]}%").where(is_nanny: true)
      if @user.address.present?
      @current_user_geocoded = current_user.geocode #=> [lat, long]
      @current_user_marker = {
          lat: @current_user_geocoded[0],
          lng: @current_user_geocoded[1],
          image_url: if @user.photo.attached? then @user.photo.key end
          
        }
      else
        
      end
      @markers = @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { user: user }),
          image_url: user.photo.key
        }
      end
      @markers << @current_user_marker
    else
      @users = User.where(is_nanny: true)
      @markers = @users.geocoded.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { user: user })
        }
      end
    end
  end

  def show
    bookings = Booking.where(nanny: @user)
    role = @user == current_user ? :nanny : :visitor
    @schedule = helpers.events_hash(bookings, role)
    @booking = Booking.new
    @parent = current_user
    @reviews = Review.where(nanny: @user)
    @avg_rating = @reviews.average(:rating)
  end

  private

  def find_index
    @user = User.find(params[:id])
  end
end
#

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def events_hash(bookings, role = :visitor)
    data = bookings.map do |booking|
      title = 'Occupied'
      duration = (booking.end_date - booking.start_date)/3600
      if role == :nanny
        title = "#{booking.parent.first_name} - #{duration}h"
      elsif role == :parent
        title = "#{booking.nanny.first_name} - #{duration}h"
      end
      if title == 'Occupied'
        color = '#F49CB0'
      else
        color = ['#F49CB0', '#F4B29C', '#CB9CF4', '#F49CDA'].sample
      end
      {
        title: title,
        start: booking.start_date.iso8601,
        end: booking.end_date.iso8601,
        backgroundColor: color,
        borderColor: color,
        url: root_path
      }
    end
    data.to_json
  end
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/show.html.erb
<div class="margin-left-show">
 <%= link_to "Go back", :back, class: "btn btn-secondary" %>
 </div>

<div class=" show-page-container">
  <div class="row">
    <div class="col overview-box">
      <h1><strong>Booking Overview</strong></h1>

      <div class="circle">
      <%= cl_image_tag @booking.nanny.photo.key, class:"avatar-very-large1", width: 300, height: 300, :gravity=>"face", crop: :thumb %>     
      </div>

      <div class="nanny-overview-text">
        <div ><strong>Name: </strong> <%= @booking.nanny.first_name %> <%= @booking.nanny.last_name %></div>
        <div><strong>Price: </strong> <%= @booking.nanny.price %> €/h</div>
        <div><strong>Age: </strong> <%= Date.today.year - @booking.nanny.year_of_birth%> years</div>
        <div><strong>Start Date: </strong> <%=@booking.start_date.strftime("%a %e %b at %l:%M%p") %></div>
        <div><strong>End Date: </strong> <%=@booking.end_date.strftime("%a %e %b at %l:%M%p") %></div>
        <% total_cost = (@booking.end_date - @booking.start_date)/3600*@booking.nanny.price.to_i %>
        <br>
        <div><strong>Total cost: </strong> <%= total_cost %> €</div>
      </div>

      <a class="btn btn-primary position-absolute-bottom" href="/dashboards">Go to dashboard</a>
      
    </div>
    <div class="col overview-box">
      <h1><strong>Live Chat</strong></h1>
        <div class="container-chat">
          <h1>#<%= @booking.id %></h1>
          <div id="messages" data-booking-id="<%= @booking.id %>">
            <% @booking.messages.each do |message| %>
              <div class="message-container" id="message-<%= message.id %>">
                <i class="author">
                  <span><%= message.user.first_name %></span>
                  <small><%= message.created_at.strftime("%a %e %b at %l:%M%p") %></small>
                </i>
                <p><%= message.content %></p>
              </div>
            <% end %>
        </div>

  <%= simple_form_for [ @booking, @message ], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "Message ##{@booking.id}" %>
  <%= f.submit 'Send' %>
<% end %>
</div>
    </div>
  </div>
</div>

app/views/chatrooms/_show.html.erb
<div class="container">
<h1>#<%= @chatroom.name %></h1>
<div id="messages" data-chatroom-id="<%= @chatroom.id %>">
  <% @chatroom.messages.each do |message| %>
    <div class="message-container" id="message-<%= message.id %>">
      <i class="author">
        <span><%= message.user.first_name %></span>
        <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
      </i>
      <p><%= message.content %></p>
    </div>
  <% end %>
</div>

<%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}" %>
  <%= f.submit 'Send' %>
<% end %>
</div>

app/views/chatrooms/show.html.erb
<div class="container">
<h1>#<%= @chatroom.name %></h1>
<div id="messages" data-chatroom-id="<%= @chatroom.id %>">
  <% @chatroom.messages.each do |message| %>
    <div class="message-container" id="message-<%= message.id %>">
      <i class="author">
        <span><%= message.user.first_name %></span>
        <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
      </i>
      <p><%= message.content %></p>
    </div>
  <% end %>
</div>

<%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}" %>
  <%= f.submit 'Send' %>
<% end %>
</div>

app/views/dashboards/index.html.erb
<div class="margin-left-show">
 <%= link_to "Go back", :back, class: "btn btn-secondary" %>
 </div>
<div class="container-custom d-flex style-margin d-flex justify-content-around">


  <div class="booking"> 
    <% @bookings.each do |booking| %>
      <div class="bookings">
        <%= link_to '', booking_path(booking), class: "far fa-times-circle text-danger x-button hover-delete", method: :delete, data: { confirm: "Are you sure?" } %>
        <% if current_user == booking.parent %>
          <div class="nanny-card">
            <%= link_to user_path(booking.nanny), class:"hover-delete" do %>
        <div class="card-product">
          <%= cl_image_tag booking.nanny.photo.key,height: 300, width: 300, class:"card-product", :gravity=>"face", crop: :thumb %>
          <div class="card-product-infos">
            <h2><%= booking.nanny.first_name %></h2><br>
            <h5 class= "right">€<%= booking.nanny.price %></h5>
            
            <% avg_rating = Review.where(nanny_id: booking.nanny_id).average(:rating) %>
            <% num = 0 %>
            <% if avg_rating != nil %>
              <% num = num + avg_rating.round %>
            <% end %>
            <% num.times do %>
              <i class="fas fa-star" style= "color: orange"></i> 
            <% end %>
            <% diff = 5 - num %>
            <% diff.times do %>
              <i class="fas fa-star" style = "color:lightgray"></i>
            <% end %>

            </div>
            </div>
            <% end %> 

            <div class= "booking__btns">
            <%if booking.status == "pending" %>
              <h5 class="status">Status: Pending  <i class="far fa-clock check-mark clock-bold"></i></h5>
            <% elsif booking.status == "confirmed" %>
              <h5 class="status">Status: Confirmed <i class="fas fa-check check-mark"></i><h5>
            <div class="buttons-dashboard-details">
            
            <% if Review.where(nanny_id: booking.nanny.id, parent_id: current_user.id).present? %>
              <% %>
            <% else %>

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-secondary review-margin" data-toggle="modal" data-target="#exampleModal">
              Write review
            </button>
          
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Write review</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="form-new">
                      <%= simple_form_for (@review) do |f| %>
                        <%= f.input :content %>
                        <%= f.input :rating %>
                        <%= f.input :nanny_id, as: :hidden, input_html: {value: booking.nanny.id} %>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <%= f.button :submit, class: "btn btn-primary" %>
                      <% end %>
                    
                  </div>
                </div>
              </div>
            </div>
           <% end %>

              
              <%= link_to "Details", booking_path(booking), class: "btn btn-primary" %>
            </div>
            
            <% end %>
              
              <% if booking.status == "pending" %>
              <div class="d-flex details-second"><%= link_to "Details", booking_path(booking), class: "btn btn-primary" %></div>
              <% end %>
              
            </div>

          </div>
        <% elsif current_user == booking.nanny %>
          <div class="parent-card">
            <div class="card-product">
            <% if booking.parent.photo.attached? %>
              <%= cl_image_tag booking.parent.photo.key, class:"card-product", :gravity=>"face", crop: :thumb %>
          <% else %>
          <%= image_tag("question_mark.jpg", size: "80x80")%>  
          <% end %>
              <div class="card-product-infos">
                <h2><%= booking.parent.first_name %></h2>
                <br>
                <h2>Children: <%= booking.parent.number_of_kids %></h2>
              </div>

            </div>
            
            <% if booking.status == "pending" %>
            <div class="buttons-accept-decline">
            <div class="div-buttons">
              <%= link_to "accept", approve_booking_path(booking), method: :post, class: "btn btn-primary m-0" %>
                <%= link_to "decline", decline_booking_path(booking), method: :post, class: "btn btn-secondary m-0" %>
                </div>
                <div class="show-booking-nanny"><%= link_to "show booking", booking_path(booking), class: "btn btn-secondary" %></div>

                </div>  
                <% else %>
                 <div class="buttons-accept-decline">
                <h5 class="status">Status: Confirmed <i class="fas fa-check check-mark"></i><h5>
                <%= link_to "Details", booking_path(booking), class: "btn btn-primary details" %>

                </div>
            <% end %>
             
             
            
             

          </div>
          
        <% end %>
      
      </div>
    <% end %>
  </div>
  <div id="calendar" class= "custom-calendar" data-agenda="<%= @schedule %>" >    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parenter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if content_for? :nav %>
    <%= content_for :nav %>
  <% else %>
    <%= render 'shared/navbar' %>
  <% end %>
    <%= render 'shared/flashes' %>




  
      <%= yield %>
 
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/messages/_message.html.erb
  
<div class="message-container" id="message-<%= message.id %>">
  <i class="author">
    <span><%= message.user.first_name %></span>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="home-page-image">
    <% content_for :nav, render('shared/custom_nav') %>
    
    <div class='wrapper'>
        <div class='banner-container'>

            <%= image_tag("Parenter-logo-2_auto_x2.png", alt: "Parenter Logo", class: "parenter-logo") %>
            <p>Find nannies</p>

            <%= link_to "GET STARTED", users_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/shared/_custom_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light custom_nav_color">
  <%= link_to root_path, class: "navbar-brand", style: "max-width:100px; margin-top: -7px;" do %>
    
  <% end %>
  <% if user_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item ">
        <%= link_to "Home", root_path, class: "nav-link-custom" %>
      </li>
     
      <li class>
        <%= link_to "Find Nanny", users_path, class: "nav-link-custom" %>
      </li>
      <li class>
        <%= link_to "My Dashboard", dashboards_path, class: "nav-link-custom" %>
      </li>
    </ul>
  <div class="nav-item dropdown center-alignment">
    <div class="circle-navbar dropdown-toggle", id= "navbarDropdown", data-toggle= "dropdown" , aria-haspopup= true, aria-expanded= false>
         <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-very-large1", width: 300, height: 300, :gravity=>"face", crop: :thumb %>
         <% else %>
         <%= image_tag("question_mark.jpg", size: "50x50")%>    
         <% end %>
      </div>
      <div class="font-white">
        <%= current_user.first_name %>
      </div>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", "/users/edit", class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% else %>
    <ul class="navbar-nav unsigned-nav ul2">
      <li>
        <%= link_to "Home", root_path, class: "nav-link-custom" %>
      </li>
      <li class="font-white">
        <%= link_to "Find Nanny", users_path, class: "nav-link-custom" %>
      </li>
      <li >
        <%= link_to "My Dashboard", dashboards_path, class: "nav-link-custom" %>
      </li>
      <li>
        <%= link_to "Log in", new_user_session_path, class: "nav-link-custom" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github mx-4"></i></a>
    <a href="#"><i class="fab fa-instagram mx-4"></i></a>
    <a href="#"><i class="fab fa-facebook mx-4"></i></a>
    <a href="#"><i class="fab fa-twitter mx-4"></i></a>
    <a href="#"><i class="fab fa-linkedin mx-4"></i></a>
  </div>
</div>
    

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Parenter-logo-2.png"%>
  <% end %>
  <% if user_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
     
      <li class>
        <%= link_to "Find Nanny", users_path, class: "nav-link" %>
      </li>
      <li class>
        <%= link_to "My Dashboard", dashboards_path, class: "nav-link" %>
      </li>
    </ul>
    <div class="nav-item dropdown center-alignment">
      <div class="circle-navbar dropdown-toggle", id= "navbarDropdown", data-toggle= "dropdown" , aria-haspopup= true, aria-expanded= false>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-very-large1", width: 300, height: 300, :gravity=>"face", crop: :thumb %>
          <% else %>
          <%= image_tag("question_mark.jpg", size: "50x50")%>  
          <% end %>
      </div>
      <div>
     <div class="font-white">
        <%= current_user.first_name %>
      </div>
      </div>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", "/users/edit", class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </div>
  <% else %>
    <ul class="navbar-nav unsigned-nav ul2">
      <li class>
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class>
        <%= link_to "Find Nanny", users_path, class: "nav-link" %>
      </li>
      <li class>
        <%= link_to "My Dashboard", dashboards_path, class: "nav-link" %>
      </li>
      <li class= "nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/users/_info_window.html.erb
<div class="info-window-container">

  <div class="circle-navbar">
    <%= cl_image_tag user.photo.key, class:"avatar-very-large1", crop: :fill %>
  </div>

  <div class="info-name-price">
    <h2 style="font-size: large;"><%= user.first_name %> </h2>
    <h2 style="font-size: large;">€ <%= user.price %></h2>
  </div>


</div>

app/views/users/index.html.erb
<div class="margin-left-show">
 <%= link_to "Go back", :back, class: "btn btn-secondary" %>
 </div>

<div class="container-custom">
<div class="users-page mb-3 mt-3">
  <div class="users-list mr-2">
    <%= form_tag users_path, method: :get, class: "user-search search-edited" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Stuttgart"%>
      <%= submit_tag "Search", class: "btn btn-primary btn-primary-form rounded-btn" %>
    <% end %>

    <div class="users-grid mb-3 mt-3">
      <% @users.each do |user| %>
        <%= link_to user_path(user), class:"hover-delete" do %>
        <div class="card-product">
          <%= cl_image_tag user.photo.key,height: 300, width: 300, class:"card-product", :gravity=>"face", crop: :thumb %>
          <div class="card-product-infos">
            <h2><%= user.first_name %></h2><br>
            <h5 class= "right">€<%= user.price %></h5>

            <% avg_rating = Review.where(nanny_id: user.id).average(:rating) %>
            <% num = 0 %>
            <% if avg_rating != nil %>
              <% num = num + avg_rating.round %>
            <% end %>
            <% num.times do %>
              <i class="fas fa-star" style= "color: orange"></i> 
            <% end %>
            <% diff = 5 - num %>
            <% diff.times do %>
              <i class="fas fa-star" style = "color:lightgray"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <% end %>
    </div>
  </div>

    
  <div id="map"
    style="width: 100%; height: 600px; border-radius: 5%; margin-left: 50px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
</div>